document.addEventListener('DOMContentLoaded', () => {
let danhsach=Array();
let tieude=Array();
let tacgia=Array();
let linkanh=Array();
let linkdownload = [];
danhsach[0] = 'https://drive.google.com/uc?id=1iZIkIFNLCY1iZrXxie5ftpvmgB0GTma5&export=download';
danhsach[1] = 'https://drive.google.com/uc?id=11ANcZiaavaB8_6COVkvG1riHUTacfe2Y&export=download';
danhsach[2] = 'https://drive.google.com/uc?id=1EVNOPpjx2j2kXJZBjwkN847qXhMyD-nm&export=download';
danhsach[3] = 'https://drive.google.com/uc?id=1WhC1EQUwTjI6KzfYsgx1nFC5JhMYexwG&export=download';
danhsach[4] = 'https://drive.google.com/uc?id=14jq19WvuppEyLwVYQimjeMy9zpkV79Qt&export=download';
danhsach[5] = 'https://drive.google.com/uc?id=1q9ok-vlyTW0EJafR09QDMmnZBf79RXY1&export=download';
danhsach[6] = 'https://drive.google.com/uc?id=1CZfsY0dxy8c1QGnWjneRUz4jf7LwL1As&export=download';
danhsach[7] = 'https://drive.google.com/uc?id=1osUpLa5WmwwYo9QP7gjzrNVbIbH_Q8mc&export=download';
danhsach[8] = 'https://drive.google.com/uc?id=1Ij3dng2BEePSiTUa3rC4FDjSzCBpvRF0&export=download';
danhsach[9] = 'https://drive.google.com/uc?id=1yLhw94_gPG5M75OnizzTGKlOm1dHFLA-&export=download';
danhsach[10] = 'https://drive.google.com/uc?id=1VrtzXK-1UCFtT_7ngqvlM1-oCgGobh8H&export=download';
danhsach[11] = 'https://drive.google.com/uc?id=1A12ivMmLudsn1Tp4G474F9dP5udCcC6Z&export=download';
danhsach[12] = 'https://drive.google.com/uc?id=1o2D4hoq6jRkYClzuaOay98c6pUIb6wLZ&export=download';
danhsach[13] = 'https://drive.google.com/uc?id=1apv22NuZLhlNI8zgX39TtiIk-UsmcAw2&export=download';
danhsach[14] = 'https://drive.google.com/uc?id=1euCqtdYrY2ms6ofXmhXeSgAvvhsoE2LB&export=download';
danhsach[15] = 'https://drive.google.com/uc?id=1GvFPjIMY0js1_mpUAfFC7xk7S9gCoB3j&export=download';
danhsach[16] = 'https://drive.google.com/uc?id=1C5B-DDhA0-yq57zlC0LtbomLZ1dX9QEB&export=download';
danhsach[17] = 'https://drive.google.com/uc?id=1dIOLQ7nvAz2LN_h6iGJNQTMT18hmmnhk&export=download';
danhsach[18] = 'https://drive.google.com/uc?id=18aFaEj152iyyMZK84hMbxdiGGTKI8WMJ&export=download';
danhsach[19] = 'https://drive.google.com/uc?id=1Oo35HgNzEYxNLY5A3IOKhbTE1jb_1AcS&export=download';
danhsach[20] = 'https://drive.google.com/uc?id=1IsiDxrY99Ddm_Zm48saTXSKKGN7myrER&export=download';
danhsach[21] = 'https://drive.google.com/uc?id=1di9pOo5NgaOBDGqMIrfKqirmkvd-Agyt&export=download';
danhsach[22] = 'https://drive.google.com/uc?id=1PKEVwCH78bxjUuk_XIE_136u1thZ9Yax&export=download';
danhsach[23] = 'https://drive.google.com/uc?id=1w4lf9Fjd0HMPDqAKMtGaeAqdkaEG3h8m&export=download';
danhsach[24] = 'https://drive.google.com/uc?id=1TgZx6h2gm4fggOg1rgI6mihzoEpVeZ-o&export=download';
danhsach[25] = 'https://drive.google.com/uc?id=1dW_vZcfAB7bh2Cy8U_Mxrkp13K5MPhkL&export=download';
danhsach[26] = 'https://drive.google.com/uc?id=1NDaRBzdtgob18XdB5Na_8H-iWLvyMnJy&export=download';
danhsach[27] = 'https://drive.google.com/uc?id=1BCJzPHMw2-s19Z9Y3-Mgai31su_nPvvm&export=download';
danhsach[28] = 'https://drive.google.com/uc?id=1UetYe5N18kjWpQoVQAOEGwW8coeeJbTq&export=download';
danhsach[29] = 'https://drive.google.com/uc?id=1tXgWst3wtWUZcOmqX3ibUbS9wxHFReYH&export=download';
danhsach[30] = 'https://drive.google.com/uc?id=1TS7jnl96jgmSj2qxS4gGiBSOYQsnxh8L&export=download';
danhsach[31] = 'https://drive.google.com/uc?id=1uPrq55xMoRGKLxcFzmOSsQVTu3JPQAQB&export=download';
danhsach[32] = 'https://drive.google.com/uc?id=1OopgUwCl3dfRa9pZaPd-KjoxkXY6p6ZH&export=download';
danhsach[33] = 'https://drive.google.com/uc?id=12Z0m6AIO0QUqut8pP9-lKMxdLaybOqMw&export=download';
danhsach[34] = 'https://drive.google.com/uc?id=1amuKhrsvnY0L060L8G6fSNofZSbvVdDu&export=download';
danhsach[35] = 'https://drive.google.com/uc?id=1mP59v_Ngt7z3yzn3hnwk1WNkcoigVRZ0&export=download';
danhsach[36] = 'https://drive.google.com/uc?id=1ayRdoceLKficGHDBN4pNKYKJWaH6RVw5&export=download';
danhsach[37] = 'https://drive.google.com/uc?id=1iLnVtBPrnQV6BEp_fZlUf0nnHKQwBJuK&export=download';
danhsach[38] = 'https://drive.google.com/uc?id=1xvZ3bkbEJjiEFGaByNSjxRpGiooVHqDn&export=download';
danhsach[39] = 'https://drive.google.com/uc?id=1HrMpGQp0XNYqnG0B4PkRhFYyaSMJN0yn&export=download';
tieude[0] = 'Chúng ta của hiện tại';
tieude[1] = 'Muốn nói với em';
tieude[2] = 'Thằng Điên';
tieude[3] = 'Có chắc yêu là đây';
tieude[4] = '3107';
tieude[5] = 'Bài này Chill phết';
tieude[6] = 'Hoa nở không màu';
tieude[7] = 'Hôn Anh';
tieude[8] = 'Một Triệu Like';
tieude[9] = 'Yêu một người có lẽ';
tieude[10] = 'Anh nhà ở đâu thế';
tieude[11] = 'Mượn rượu tỏ tình';
tieude[12] = 'Người âm phủ';
tieude[13] = 'Really Love You';
tieude[14] = 'Yêu 5';
tieude[15] = 'Tâm sự tuổi 30';
tieude[16] = "We don't talk any more";
tieude[17] = 'Sugar';
tieude[18] = 'Blank Space';
tieude[19] = 'Uptown Funk';
tieude[20] = 'Let Her Go';
tieude[21] = 'Havana';
tieude[22] = 'Baby';
tieude[23] = 'Fade';
tieude[24] = 'Waiting for Love';
tieude[25] = 'At My Worst';
tieude[26] = 'Girls Like You';
tieude[27] = 'Closer';
tieude[28] = 'That Girl';
tieude[29] = 'Shape of You';
tieude[30] = 'See You Again';
tieude[31] = 'The Ocean';
tieude[32] = 'Flowers';
tieude[33] = 'Shutdown';
tieude[34] = 'Dynamite';
tieude[35] = 'Tabun';
tieude[36] = 'Lemon';
tieude[37] = 'Gangnam Style';
tieude[38] = 'Sakura Anata de Aete Yokatta';
tieude[39] = 'Shinunoga E-wa';
tacgia[0] = 'Sơn Tùng MTP';
tacgia[1] = 'Tteam X Blackbi';
tacgia[2] = 'VirusS & JustaTee';
tacgia[3] = 'Sơn Tùng MTP';
tacgia[4] = 'ft. Nâu, Duongg, Titie';
tacgia[5] = 'Đen Vâu ft Min';
tacgia[6] = 'Hoài Lâm';
tacgia[7] = 'Min';
tacgia[8] = 'Đen ft. Thành Đồng';
tacgia[9] = 'Miule ft Lou Hoàng';
tacgia[10] = 'Amee & Bray';
tacgia[11] = 'Emily ft BigDaddy';
tacgia[12] = 'Osad ft Khánh Vy';
tacgia[13] = 'Noo Phước Thịnh';
tacgia[14] = 'Rhymastic';
tacgia[15] = 'Trịnh Thăng Bình';
tacgia[16] = 'Charlie Puth';
tacgia[17] = 'Maroon 5';
tacgia[18] = 'Taylor Swift';
tacgia[19] = 'Mark Ronson ft. Bruno Mars';
tacgia[20] = 'Passenger';
tacgia[21] = 'Camila Cabello ft. Young Thug';
tacgia[22] = 'Justin Bieber';
tacgia[23] = 'Alan Walker';
tacgia[24] = 'Avicii';
tacgia[25] = 'Pink Sweat$';
tacgia[26] = 'Maroon 5 ft. Cardi B';
tacgia[27] = 'The Chainsmokers ft. Halsey';
tacgia[28] = 'Olly Murs';
tacgia[29] = 'Ed Sheeran';
tacgia[30] = 'Wiz Khalifa ft. Charlie Puth';
tacgia[31] = 'Mike Perry ft. Shy Martin';
tacgia[32] = 'Jisoo';
tacgia[33] = 'BlackPink';
tacgia[34] = 'BTS';
tacgia[35] = 'YASOBI';
tacgia[36] = 'Kenshi Yonezu';
tacgia[37] = 'PSY';
tacgia[38] = '5cm/s';
tacgia[39] = 'Fujii Kaze';
linkanh[0] = 'acsset/img/V-POP/chungtacuahientai.jpg';
linkanh[1] = 'acsset/img/V-POP/muonnoivoiem.jpg';
linkanh[2] = 'acsset/img/V-POP/thangdien.jpg';
linkanh[3] = 'acsset/img/V-POP/cochacyeuladay.jpg';
linkanh[4] = 'acsset/img/V-POP/3107.jpg';
linkanh[5] = 'acsset/img/V-POP/bainaychillphet.jpg';
linkanh[6] = 'acsset/img/V-POP/hoanokhongmau.jpg';
linkanh[7] = 'acsset/img/V-POP/honanh.jpg';
linkanh[8] = 'acsset/img/V-POP/1-trieu-like.png';
linkanh[9] = 'acsset/img/V-POP/yeu1nguoicole.jpg';
linkanh[10] = 'acsset/img/V-POP/anhnhaodauthe.jpg';
linkanh[11] = 'acsset/img/V-POP/muonruoutotinh.jpg';
linkanh[12] = 'acsset/img/V-POP/nguoiamphu.jpg';
linkanh[13] = 'acsset/img/V-POP/reallyloveu.jpg';
linkanh[14] = 'acsset/img/V-POP/yeu5.jpg'; 
linkanh[15] = 'acsset/img/V-POP/tamsutuoi30.jpg';
linkanh[16] = 'acsset/img/US-UK/wedonttalkanymore.jpg';
linkanh[17] = 'acsset/img/US-UK/sugar.jpg';
linkanh[18] = 'acsset/img/US-UK/blankspace.jpg';
linkanh[19] = 'acsset/img/US-UK/uptownfunk.jpg';
linkanh[20] = 'acsset/img/US-UK/lethergo.jpg';
linkanh[21] = 'acsset/img/US-UK/havana.jpg';
linkanh[22] = 'acsset/img/US-UK/baby.jpg';
linkanh[23] = 'acsset/img/US-UK/fade.jpg';
linkanh[24] = 'acsset/img/US-UK/waitingforlove.jpg';
linkanh[25] = 'acsset/img/US-UK/atmyworst.jpg';
linkanh[26] = 'acsset/img/US-UK/girllikeyou.jpg';
linkanh[27] = 'acsset/img/US-UK/closer.jpg';
linkanh[28] = 'acsset/img/US-UK/thatgirl.jpg';
linkanh[29] = 'acsset/img/US-UK/shapeofu.jpg';
linkanh[30] = 'acsset/img/US-UK/seeyouagain.jpg';
linkanh[31] = 'acsset/img/US-UK/ocean.jpg';
linkanh[32] = 'acsset/img/K - POP & J - POP/Flowers.png';
linkanh[33] = 'acsset/img/K - POP & J - POP/shutdown.jpg';
linkanh[34] = 'acsset/img/K - POP & J - POP/dynamite.jpg';
linkanh[35] = 'acsset/img/K - POP & J - POP/tabun.jpg';
linkanh[36] = 'acsset/img/K - POP & J - POP/lemon.jpg';
linkanh[37] = 'acsset/img/K - POP & J - POP/gangnamstyle.jpg';
linkanh[38] = 'acsset/img/K - POP & J - POP/sakura anata deaete yokatta.jpg';
linkanh[39] = 'acsset/img/K - POP & J - POP/shinunoga.jpg';
danhsach[40] = 'https://drive.google.com/uc?id=1FhWwjANZpgRtQefcChxDnpfbbbQpePMu&export=download';
danhsach[41] = 'https://drive.google.com/uc?id=1ttcB14QlaNxbLoIHndWVvD7e2yyXhnmB&export=download';
danhsach[42] = 'https://drive.google.com/uc?id=1-QbAvLpDlYGXbptG9MJ9mmwuNBF1yij4&export=download';
tieude[40] = 'Chúng ta không thuộc về nhau';
tieude[41] = 'Không phải dạng vừa đâu';
tieude[42] = 'Hãy trao cho anh';
tacgia[40] = 'Sơn Tùng M-TP';
tacgia[41] = 'Sơn Tùng M-TP';
tacgia[42] = 'Sơn Tùng M-TP';
linkanh[40] = 'acsset/img/V-POP/chungtakhongthuocvenhau.jpg';
linkanh[41] = 'acsset/img/V-POP/khongphaidangvuadau.jpg';
linkanh[42] = 'acsset/img/V-POP/haytraochoanh.jpg';
linkdownload[0] = 'https://drive.google.com/uc?id=1iZIkIFNLCY1iZrXxie5ftpvmgB0GTma5&export=download';
linkdownload[1] = 'https://drive.google.com/uc?id=11ANcZiaavaB8_6COVkvG1riHUTacfe2Y&export=download';
linkdownload[2] = 'https://drive.google.com/uc?id=1EVNOPpjx2j2kXJZBjwkN847qXhMyD-nm&export=download';
linkdownload[3] = 'https://drive.google.com/uc?id=1WhC1EQUwTjI6KzfYsgx1nFC5JhMYexwG&export=download';
linkdownload[4] = 'https://drive.google.com/uc?id=14jq19WvuppEyLwVYQimjeMy9zpkV79Qt&export=download';
linkdownload[5] = 'https://drive.google.com/uc?id=1q9ok-vlyTW0EJafR09QDMmnZBf79RXY1&export=download';
linkdownload[6] = 'https://drive.google.com/uc?id=1CZfsY0dxy8c1QGnWjneRUz4jf7LwL1As&export=download';
linkdownload[7] = 'https://drive.google.com/uc?id=1osUpLa5WmwwYo9QP7gjzrNVbIbH_Q8mc&export=download';
linkdownload[8] = 'https://drive.google.com/uc?id=1Ij3dng2BEePSiTUa3rC4FDjSzCBpvRF0&export=download';
linkdownload[9] = 'https://drive.google.com/uc?id=1yLhw94_gPG5M75OnizzTGKlOm1dHFLA-&export=download';
linkdownload[10] = 'https://drive.google.com/uc?id=1VrtzXK-1UCFtT_7ngqvlM1-oCgGobh8H&export=download';
linkdownload[11] = 'https://drive.google.com/uc?id=1A12ivMmLudsn1Tp4G474F9dP5udCcC6Z&export=download';
linkdownload[12] = 'https://drive.google.com/uc?id=1o2D4hoq6jRkYClzuaOay98c6pUIb6wLZ&export=download';
linkdownload[13] = 'https://drive.google.com/uc?id=1apv22NuZLhlNI8zgX39TtiIk-UsmcAw2&export=download';
linkdownload[14] = 'https://drive.google.com/uc?id=1euCqtdYrY2ms6ofXmhXeSgAvvhsoE2LB&export=download';
linkdownload[15] = 'https://drive.google.com/uc?id=1GvFPjIMY0js1_mpUAfFC7xk7S9gCoB3j&export=download';
linkdownload[16] = 'https://drive.google.com/uc?id=1C5B-DDhA0-yq57zlC0LtbomLZ1dX9QEB&export=download';
linkdownload[17] = 'https://drive.google.com/uc?id=1dIOLQ7nvAz2LN_h6iGJNQTMT18hmmnhk&export=download';
linkdownload[18] = 'https://drive.google.com/uc?id=18aFaEj152iyyMZK84hMbxdiGGTKI8WMJ&export=download';
linkdownload[19] = 'https://drive.google.com/uc?id=1Oo35HgNzEYxNLY5A3IOKhbTE1jb_1AcS&export=download';
linkdownload[20] = 'https://drive.google.com/uc?id=1IsiDxrY99Ddm_Zm48saTXSKKGN7myrER&export=download';
linkdownload[21] = 'https://drive.google.com/uc?id=1di9pOo5NgaOBDGqMIrfKqirmkvd-Agyt&export=download';
linkdownload[22] = 'https://drive.google.com/uc?id=1PKEVwCH78bxjUuk_XIE_136u1thZ9Yax&export=download';
linkdownload[23] = 'https://drive.google.com/uc?id=1w4lf9Fjd0HMPDqAKMtGaeAqdkaEG3h8m&export=download';
linkdownload[24] = 'https://drive.google.com/uc?id=1TgZx6h2gm4fggOg1rgI6mihzoEpVeZ-o&export=download';
linkdownload[25] = 'https://drive.google.com/uc?id=1dW_vZcfAB7bh2Cy8U_Mxrkp13K5MPhkL&export=download';
linkdownload[26] = 'https://drive.google.com/uc?id=1NDaRBzdtgob18XdB5Na_8H-iWLvyMnJy&export=download';
linkdownload[27] = 'https://drive.google.com/uc?id=1BCJzPHMw2-s19Z9Y3-Mgai31su_nPvvm&export=download';
linkdownload[28] = 'https://drive.google.com/uc?id=1UetYe5N18kjWpQoVQAOEGwW8coeeJbTq&export=download';
linkdownload[29] = 'https://drive.google.com/uc?id=1tXgWst3wtWUZcOmqX3ibUbS9wxHFReYH&export=download';
linkdownload[30] = 'https://drive.google.com/uc?id=1TS7jnl96jgmSj2qxS4gGiBSOYQsnxh8L&export=download';
linkdownload[31] = 'https://drive.google.com/uc?id=1uPrq55xMoRGKLxcFzmOSsQVTu3JPQAQB&export=download';
linkdownload[32] = 'https://drive.google.com/uc?id=1OopgUwCl3dfRa9pZaPd-KjoxkXY6p6ZH&export=download';
linkdownload[33] = 'https://drive.google.com/uc?id=12Z0m6AIO0QUqut8pP9-lKMxdLaybOqMw&export=download';
linkdownload[34] = 'https://drive.google.com/uc?id=1amuKhrsvnY0L060L8G6fSNofZSbvVdDu&export=download';
linkdownload[35] = 'https://drive.google.com/uc?id=1mP59v_Ngt7z3yzn3hnwk1WNkcoigVRZ0&export=download';
linkdownload[36] = 'https://drive.google.com/uc?id=1ayRdoceLKficGHDBN4pNKYKJWaH6RVw5&export=download';
linkdownload[37] = 'https://drive.google.com/uc?id=1iLnVtBPrnQV6BEp_fZlUf0nnHKQwBJuK&export=download';
linkdownload[38] = 'https://drive.google.com/uc?id=1xvZ3bkbEJjiEFGaByNSjxRpGiooVHqDn&export=download';
linkdownload[39] = 'https://drive.google.com/uc?id=1HrMpGQp0XNYqnG0B4PkRhFYyaSMJN0yn&export=download';
linkdownload[40] = 'https://drive.google.com/uc?id=1FhWwjANZpgRtQefcChxDnpfbbbQpePMu&export=download';
linkdownload[41] = 'https://drive.google.com/uc?id=1ttcB14QlaNxbLoIHndWVvD7e2yyXhnmB&export=download';
linkdownload[42] = 'https://drive.google.com/uc?id=1-QbAvLpDlYGXbptG9MJ9mmwuNBF1yij4&export=download';
linkdownload[43] = 'https://drive.google.com/uc?id=1_1CeoSIzWKpFDnatgFAyIfAkt715m6Od&export=download';
linkdownload[44] = 'https://drive.google.com/uc?id=1ZehAO4LkMS5v0f515i8kukXZQrv8n6BL&export=download';
linkdownload[45] = 'https://drive.google.com/uc?id=11CvAk6i4NmfnDj_hOnpKo5_adR2yz7fH&export=download';
linkdownload[46] = 'https://drive.google.com/uc?id=1FMn1JxlzRzA_Z2qhdaOpOkUqif63iUqV&export=download';
linkdownload[47] = 'https://drive.google.com/uc?id=1zwCgn0i7Ll0EcQTMvkCiY1uFA_Ie1bOU&export=download';
linkdownload[48] = 'https://drive.google.com/uc?id=1bDRUdYqDmIQXX_hNDwtZpv3u5292CUn0&export=download';
linkdownload[49] = 'https://drive.google.com/uc?id=1rAb1-wzUcPJhKZVfs8v4ekGd3qB99Usl&export=download';
linkdownload[50] = 'https://drive.google.com/uc?id=1N6bASxFhcnzVqAbIt9MzyeAYGuzY2T8V&export=download';
linkdownload[51] = 'https://drive.google.com/uc?id=18PdRXT5UGA06FzvNqajB4C8RbCkwCVEQ&export=download';
linkdownload[52] = 'https://drive.google.com/uc?id=1HR1S_QkTQ3KBwViaDnGda7faKTXEtV5r&export=download';
linkdownload[53] = 'https://drive.google.com/uc?id=1Du8onoisIk4qazw_zxrclux-iLvCsjJF&export=download';
linkdownload[54] = 'https://drive.google.com/uc?id=1AqmJJkB7IEgjoCpYA9PkenfF5nee6lPm&export=download';
linkdownload[55] = 'https://drive.google.com/uc?id=1XtlCjGeefRgwb3PzDsVOA3Hnc0yUZCLv&export=download';
linkdownload[56] = 'https://drive.google.com/uc?id=1p5qFR7fhlC-nLDHvcAeS_tfqgmEF0q0-&export=download';
linkdownload[57] = 'https://drive.google.com/uc?id=11ryHN4wLBTfqwAniwf18Ot1wj8pRdW76&export=download';
linkdownload[58] = 'https://drive.google.com/uc?id=1hYiAnoWx0DVFDH9jYTV6Q_q-0sSUcZxV&export=download';
linkdownload[59] = 'https://drive.google.com/uc?id=1t47dk1XCMzWI6fL7-o78JNl7aw3HCwxo&export=download';
linkdownload[60] = 'https://drive.google.com/uc?id=1cDBFfMq4mPdEQDbSeVI624apP0XzZnAR&export=download';
linkdownload[61] = 'https://drive.google.com/uc?id=1hTWD8E0Z8nuEJDn2KqHinB1Skysqla7J&export=download';
linkdownload[62] = 'https://drive.google.com/uc?id=1M8x8nhSkeEo_BrqxfcMm_8jdCBb1wysv&export=download';
linkdownload[63] = 'https://drive.google.com/uc?id=1z9_zb2WYk3zAXkVd4GhuxhXWtmM12Ely&export=download';
linkdownload[64] = 'https://drive.google.com/uc?id=1hqx8zismU9_PMkvOLZa_dZm6y8mBJgq5&export=download';
linkdownload[65] = 'https://drive.google.com/uc?id=1Yz2sUA94wW_qo-RSVl6mZo-c6ViB9QiM&export=download';
linkdownload[66] = 'https://drive.google.com/uc?id=1QZ6BBYhX05pZjqKosdhU5J_BisP-aFjQ&export=download';
linkdownload[67] = 'https://drive.google.com/uc?id=1sxoc3NOqLqUrhfD1f5Z-o3_43qKVgXt5&export=download';
linkdownload[68] = 'https://drive.google.com/uc?id=1QOFn2r9lUnnjDiwF1Fv0vzEcIMeGFzsP&export=download';
linkdownload[69] = 'https://drive.google.com/uc?id=1oLdW1-fxQEs5Ts-RL1VsZs0Jq2AiBcJi&export=download';
linkdownload[70] = 'https://drive.google.com/uc?id=1sMe1WDS6dD0tUoM0ZkoX0z3h1Izp6M7s&export=download';
linkdownload[71] = 'https://drive.google.com/uc?id=10li06TSuXtR6ILneTCI5U37q_0q_Df3k&export=download';
linkdownload[72] = 'https://drive.google.com/uc?id=1KpOo-tiObuCVnmmCRFJfsRdnptFljQCS&export=download';
linkdownload[73] = 'https://drive.google.com/uc?id=1ZopmCzDYsp58WcGS2a-RCxj27L9SpwP7&export=download';
linkdownload[74] = 'https://drive.google.com/uc?id=1WDc1lmZMvdMk0vnoOU7BZpGY8HS0cT9H&export=download';
danhsach[43] = 'https://drive.google.com/uc?id=1_1CeoSIzWKpFDnatgFAyIfAkt715m6Od&export=download';
danhsach[44] = 'https://drive.google.com/uc?id=1ZehAO4LkMS5v0f515i8kukXZQrv8n6BL&export=download';
danhsach[45] = 'https://drive.google.com/uc?id=11CvAk6i4NmfnDj_hOnpKo5_adR2yz7fH&export=download';
danhsach[46] = 'https://drive.google.com/uc?id=1FMn1JxlzRzA_Z2qhdaOpOkUqif63iUqV&export=download';
danhsach[47] = 'https://drive.google.com/uc?id=1zwCgn0i7Ll0EcQTMvkCiY1uFA_Ie1bOU&export=download';
danhsach[48] = 'https://drive.google.com/uc?id=1bDRUdYqDmIQXX_hNDwtZpv3u5292CUn0&export=download';
danhsach[49] = 'https://drive.google.com/uc?id=1rAb1-wzUcPJhKZVfs8v4ekGd3qB99Usl&export=download';
danhsach[50] = 'https://drive.google.com/uc?id=1N6bASxFhcnzVqAbIt9MzyeAYGuzY2T8V&export=download';
danhsach[51] = 'https://drive.google.com/uc?id=18PdRXT5UGA06FzvNqajB4C8RbCkwCVEQ&export=download';
danhsach[52] = 'https://drive.google.com/uc?id=1HR1S_QkTQ3KBwViaDnGda7faKTXEtV5r&export=download';
danhsach[53] = 'https://drive.google.com/uc?id=1Du8onoisIk4qazw_zxrclux-iLvCsjJF&export=download';
danhsach[54] = 'https://drive.google.com/uc?id=1AqmJJkB7IEgjoCpYA9PkenfF5nee6lPm&export=download';
danhsach[55] = 'https://drive.google.com/uc?id=1XtlCjGeefRgwb3PzDsVOA3Hnc0yUZCLv&export=download';
danhsach[56] = 'https://drive.google.com/uc?id=1p5qFR7fhlC-nLDHvcAeS_tfqgmEF0q0-&export=download';
danhsach[57] = 'https://drive.google.com/uc?id=11ryHN4wLBTfqwAniwf18Ot1wj8pRdW76&export=download';
danhsach[58] = 'https://drive.google.com/uc?id=1hYiAnoWx0DVFDH9jYTV6Q_q-0sSUcZxV&export=download';
danhsach[59] = 'https://drive.google.com/uc?id=1t47dk1XCMzWI6fL7-o78JNl7aw3HCwxo&export=download';
danhsach[60] = 'https://drive.google.com/uc?id=1cDBFfMq4mPdEQDbSeVI624apP0XzZnAR&export=download';
danhsach[61] = 'https://drive.google.com/uc?id=1hTWD8E0Z8nuEJDn2KqHinB1Skysqla7J&export=download';
danhsach[62] = 'https://drive.google.com/uc?id=1M8x8nhSkeEo_BrqxfcMm_8jdCBb1wysv&export=download';
danhsach[63] = 'https://drive.google.com/uc?id=1z9_zb2WYk3zAXkVd4GhuxhXWtmM12Ely&export=download';
danhsach[64] = 'https://drive.google.com/uc?id=1hqx8zismU9_PMkvOLZa_dZm6y8mBJgq5&export=download';
danhsach[65] = 'https://drive.google.com/uc?id=1Yz2sUA94wW_qo-RSVl6mZo-c6ViB9QiM&export=download';
danhsach[66] = 'https://drive.google.com/uc?id=1QZ6BBYhX05pZjqKosdhU5J_BisP-aFjQ&export=download';
danhsach[67] = 'https://drive.google.com/uc?id=1sxoc3NOqLqUrhfD1f5Z-o3_43qKVgXt5&export=download';
danhsach[68] = 'https://drive.google.com/uc?id=1QOFn2r9lUnnjDiwF1Fv0vzEcIMeGFzsP&export=download';
danhsach[69] = 'https://drive.google.com/uc?id=1oLdW1-fxQEs5Ts-RL1VsZs0Jq2AiBcJi&export=download';
danhsach[70] = 'https://drive.google.com/uc?id=1sMe1WDS6dD0tUoM0ZkoX0z3h1Izp6M7s&export=download';
danhsach[71] = 'https://drive.google.com/uc?id=10li06TSuXtR6ILneTCI5U37q_0q_Df3k&export=download';
danhsach[72] = 'https://drive.google.com/uc?id=1KpOo-tiObuCVnmmCRFJfsRdnptFljQCS&export=download';
danhsach[73] = 'https://drive.google.com/uc?id=1ZopmCzDYsp58WcGS2a-RCxj27L9SpwP7&export=download';
danhsach[74] = 'https://drive.google.com/uc?id=1WDc1lmZMvdMk0vnoOU7BZpGY8HS0cT9H&export=download';
tieude[43] = 'Making My Way';
tieude[44] = 'Một ngày chẳng nắng';
tieude[45] = 'Nấu ăn cho em';
tieude[46] = 'Vũ trụ có anh';
tieude[47] = 'Fall in love Alone';
tieude[48] = 'Chạm gần thêm thương';
tieude[49] = 'Herw with me';
tieude[50] = 'Overdose';
tieude[51] = 'Attention';
tieude[52] = 'Collide';
tieude[53] = 'Shake it off(SpeedUp)';
tieude[54] = 'Give it to me';
tieude[55] = 'Call me maybe';
tieude[56] = 'Cà phê(SpeedUp)';
tieude[57] = 'Baby(SpeedUp)';
tieude[58] = 'Happier';
tieude[59] = 'Cupid(SpeedUp)';
tieude[60] = 'Pano(Speedup)';
tieude[61] = 'How long(SpeedUp)';
tieude[62] = 'See tình(SpeedUp)';
tieude[63] = 'Under Thein Fluence';
tieude[64] = 'Levitating';
tieude[65] = 'That was I like';
tieude[66] = 'Again';
tieude[67] = 'Cai thuốc';
tieude[68] = 'Bất vấn biệt ly';
tieude[69] = 'Dã Tử';
tieude[70] = 'Đối Tửu';
tieude[71] = 'Gả';
tieude[72] = 'Hạ Sơn';
tieude[73] = 'Thanh Trừ';
tieude[74] = 'Giày cao gót màu đỏ';
tacgia[43] = 'Sơn Tùng MTP';
tacgia[44] = 'Pháo Northside';
tacgia[45] = 'Đen Vâu ft. PiaLinh';
tacgia[46] = 'Phương Mỹ Chi ft. Pháo Northside';
tacgia[47] = 'Stacey Ryan';
tacgia[48] = 'Trúc Nhân';
tacgia[49] = 'D4vd';
tacgia[50] = 'なとり / ver. Shoto';
tacgia[51] = 'Charlie Puth';
tacgia[52] = 'Justine Skye ft. Tyga';
tacgia[53] = 'Taylor Swift';
tacgia[54] = 'Nelly Furtado ft Justin Timberlake';
tacgia[55] = 'Carly Rae Jepsen';
tacgia[56] = 'Min';
tacgia[57] = 'Justin Bieber';
tacgia[58] = 'Marshmello ft. Bastille';
tacgia[59] = 'Fifty Fifty';
tacgia[60] = 'Zack Tabudlo';
tacgia[61] = 'Charlie Puth';
tacgia[62] = 'Hoàng Thùy Linh';
tacgia[63] = 'Chris Brown';
tacgia[64] = 'Dua Lipa';
tacgia[65] = 'Bruno Mars';
tacgia[66] = 'Shiloh dynasty';
tacgia[67] = 'Lý Vinh Hạo';
tacgia[68] = 'Chỉ Tiêm Tiếu';
tacgia[69] = 'Tô Vận Doanh';
tacgia[70] = 'Trương Thiên Ảnh';
tacgia[71] = 'Chấp Tố Hề';
tacgia[72] = 'Khanh Quân';
tacgia[73] = 'Vương Hân Thần & Tô Tinh Hân';
tacgia[74] = 'Thái Kiện Nhã';
linkanh[43] = 'acsset/img/New realese/makingmyway.png';
linkanh[44] = 'acsset/img/New realese/motngaychangnang.png';
linkanh[45] = 'acsset/img/New realese/nauanchoem.png';
linkanh[46] = 'acsset/img/New realese/vutrucoanh.png';
linkanh[47] = 'acsset/img/New realese/fallinlovealone.png';
linkanh[48] = 'acsset/img/New realese/chamganthemthuong.png';
linkanh[49] = 'acsset/img/New realese/herewithme.png';
linkanh[50] = 'acsset/img/New realese/overdose.png';
linkanh[51] = 'acsset/img/Speedup/attention.png';
linkanh[52] = 'acsset/img/Speedup/colide.png';
linkanh[53] = 'acsset/img/Speedup/Shakeitoff.png';
linkanh[54] = 'acsset/img/Speedup/giveittome.png';
linkanh[55] = 'acsset/img/Speedup/callmemaybe.png';
linkanh[56] = 'acsset/img/Speedup/caphe.png';
linkanh[57] = 'acsset/img/Speedup/baby.png';
linkanh[58] = 'acsset/img/Speedup/happier.png';
linkanh[59] = 'acsset/img/Speedup/cupid.png';
linkanh[60] = 'acsset/img/Speedup/pano.png';
linkanh[61] = 'acsset/img/Speedup/howlong.png';
linkanh[62] = 'acsset/img/Speedup/seetinh.png';
linkanh[63] = 'acsset/img/Speedup/undertheinfluence.png';
linkanh[64] = 'acsset/img/Speedup/levitating.png';
linkanh[65] = 'acsset/img/Speedup/thatwasilike.png';
linkanh[66] = 'acsset/img/Speedup/again.png';
linkanh[67] = 'acsset/img/C-Pop/caithuoc.png';
linkanh[68] = 'acsset/img/C-Pop/batvanbietly.png';
linkanh[69] = 'acsset/img/C-Pop/datu.png';
linkanh[70] = 'acsset/img/C-Pop/doituu.png';
linkanh[71] = 'acsset/img/C-Pop/ga.png';
linkanh[72] = 'acsset/img/C-Pop/hason.png';
linkanh[73] = 'acsset/img/C-Pop/thanhtru.png';
linkanh[74] = 'acsset/img/C-Pop/giaycaogotmaudo.png';
window.danhsach = danhsach;
window.tieude = tieude;
window.tacgia = tacgia;
window.linkanh = linkanh;
window.linkdownload = linkdownload;
});